### ISSUE TITLE
Can't run test examples

### ISSUE THREAD

**Issue by JackHowa** [emazzotta/lighthouse-badges#29]
- thanks for setting this up. I used to use the https://github.com/ebidel/lighthouse-badge/issues/5 badge but this seems cooler with automation 

### Steps to Reproduce

1.` npx lighthouse-badges --urls https://www.youtube.com/ https://www.youtube.com/feed/trending -o test_results`

### Expected Behaviour

- no error, I guess I should see an output 

### Actual Behaviour

- error, no output 

### Stacktrace

```
npx: installed 270 in 11.486s

npx: installed 270 in 12.939s
  ◜ Running Lighthouse, please wait...Error: Command failed: /Users/howardj/.npm/_npx/81364/lib/node_modules/lighthouse-badges/node_modules/.bin/lighthouse --chrome-flags='--headless --no-sandbox --no-default-browser-check --no-first-run --disable-default-apps' --output=json --output-path=stdout --quiet  https://www.youtube.com/
/Users/howardj/.npm/_npx/81364/lib/node_modules/lighthouse-badges/node_modules/lighthouse/lighthouse-core/gather/driver.js:68
  _traceCategories = Driver.traceCategories;
                   ^

SyntaxError: Unexpected token =
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

```

### Environment Information

- **Operating System**: 10.15.7 (19H15) Catalina MacOS
- **Lighthouse-Badges Version:** 1.1.0
- **Node Version:** v10.15.3

### Additional Information 

(Please tick where applicable)
- [x] The issue persists with the npm version (same stacktrace, tried global install)
- [x] The issue persists with the docker version (different stacktrace, see below) 

```
  ◟ Running Lighthouse, please wait...Error: Command failed: /home/lighthouse/node_modules/.bin/lighthouse --chrome-flags='--headless --no-sandbox --no-default-browser-check --no-first-run --disable-default-apps' --output=json --output-path=stdout --quiet  https://www.youtube.com/feed/trending
Runtime error encountered: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Runtime.evaluate)
LHError: PROTOCOL_TIMEOUT
    at Timeout._onTimeout (/home/lighthouse/node_modules/lighthouse/lighthouse-core/gather/driver.js:399:21)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by emazzotta** [comment]
Hi @JackHowa 

Thanks for the bug report. 

You mention you're using node 10. Unfortunately this version is not supported.
Node version 15 should work fine, but an upgrade to at least version 12 should also do the trick.
Can you verify this works for you?

Also, the timeout issue with docker should be solved now.
If you pull the latest image `docker pull emazzotta/lighthouse-badges:latest` it shouldn't fail anymore.

**Comment by JackHowa** [comment]
awesome thanks @emazzotta ! verified node 12. thanks for adding to the readme as well 

```
learning % nvm use 12.16.3
Now using node v12.16.3 (npm v6.14.4)
 learning % npx lighthouse-badges --urls https://www.youtube.com/ https://www.youtube.com/feed/trending -o test_results


npx: installed 270 in 13.312s
Saved svg to test_results/lighthouse_performance.svg
Saved svg to test_results/lighthouse_pwa.svg
Saved svg to test_results/lighthouse_seo.svg
Saved svg to test_results/lighthouse_best-practices.svg
Saved svg to test_results/lighthouse_accessibility.svg
